name: menetrend
description: Menetrend demo
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  http:
  cupertino_icons: ^1.0.0
  flutter_feather_icons: ^1.0.3
  textfield_search: any
  dynamic_theme:
    git:
      url: https://github.com/Norbert515/dynamic_theme

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true